# Flask
FLASK_SERVER_PORT = 5005
FLASK_SERVER_NAME = 'localhost:%s' % FLASK_SERVER_PORT
FLASK_DEBUG = False  # Do not use debug mode in production
FLASK_USE_RELOADER = False

# Flask-Restplus settings
RESTPLUS_SWAGGER_UI_DOC_EXPANSION = 'list'
RESTPLUS_VALIDATE = True
RESTPLUS_MASK_SWAGGER = False
RESTPLUS_ERROR_404_HELP = False

# SQLAlchemy settings
SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS = False
